// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHr9toSGpo4Ox_k5YbbwXmX_j8WPr1cTA',
    appId: '1:595130111925:android:bbc4d8c5a97e60c0e92bfc',
    messagingSenderId: '595130111925',
    projectId: 'fir-tutorial-a0710',
    storageBucket: 'fir-tutorial-a0710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe5r2r2NO4MIzFaUxl2Zq6TdYxtLihXbM',
    appId: '1:595130111925:ios:b4e249c1d5a44f25e92bfc',
    messagingSenderId: '595130111925',
    projectId: 'fir-tutorial-a0710',
    storageBucket: 'fir-tutorial-a0710.appspot.com',
    iosClientId: '595130111925-oqiitu43h4c9u6m75rqhe2kcjk1h5ig2.apps.googleusercontent.com',
    iosBundleId: 'com.junichi.goRoutetRedirect',
  );
}
